version: "3"
services:
  db:
    image: mongo
    volumes:
      - mongovolume:/data/db
  nodeexpress:
    build: "."
    ports:
      # - "${PORT}:${PORT}"
      - "3000:3000"
    restart: always
    volumes:
      - ./src:/app/src #for rebuild on file change
    env_file:
      - .env
    depends_on:
      - db
volumes:
  mongovolume:
