version: "3"
services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  nestapp:
    build: "."
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./:/app/ #for rebuild on file change
volumes:
  postgres:
